baseurl = "https://sleephu.github.io"
title = "jyh.im"
theme = "vec"
languageCode = "en-us"
paginate = 10
disqusShortname = ""
googleAnalytics = "UA-75736312-2"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "post"
    weight = 0
    url = "https://sleephu.github.io/post"
  [[menu.main]]
    name = "contact"
    weight = 1
    url = "https://sleephu.github.io/contact"
  [[menu.main]]
    name = "study"
    weight = 2
    url = "https://sleephu.github.io/study"
  [[menu.main]]
    name = "lsz"
    weight = 0
    url = "https://sleephu.github.io/lsz"

[params]
  Keywords = "key, 关键字, キーワード"
  Description = "There are some words to describe your site"
  Avatar = "img/avatar.jpg"
  SelfIntro = "Problem solver, data driven thinker, and self-motivated learner."
  Email = "jingyunhu.cr@gmail.com"

  GithubID = "sleephu"
  LinkedInID = "jingyunhu"
