baseurl = "https://sleephu.github.io"
title = "jyh.im"
theme = "vec"
languageCode = "en-us"
paginate = 10
disqusShortname = ""
googleAnalytics = ""

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "post"
    weight = 0
    url = "/post"
  [[menu.main]]
    name = "contact"
    weight = 1
    url = "/contact"
  [[menu.main]]
    name = "faq"
    weight = 2
    url = "/faq"

[params]
  Keywords = "key, 关键字, キーワード"
  Description = "There are some words to describe your site"
  Avatar = "img/avatar.jpg"
  SelfIntro = "Just a worm, seek for true, live in shadow, no more..."
  Email = "jingyunhu.cr@gmail.com"

  GithubID = "sleephu"
  TwitterID = "Your Twitter ID"
  FacebookID = "Your Facebook ID"
  LinkedInID = "jingyunhu"
  GoogleplusID = "Your Googleplus ID"
